# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.6
  - 5.4

script: phpunit -c app/ --coverage-text

before_script:
  - composer self-update
  - composer install -n

notifications:
  email: med.ahamada@mit.co.ma
  slack: 'devs-mit: T4k7lDZSrNjGm4tje17Mbmro'
