bean_homepage:
    path:     /hello/{name}
    defaults: { _controller: beanBundle:Default:index }

verAddCompte:
    path:     /ajouter
    defaults: {_controller: beanBundle:Default:versAddCompteForm}

create:
    path:     /create
    defaults: {_controller: beanBundle:Default:saveCompte}

listComptes:
    path:     /Comptes
    defaults: {_controller: beanBundle:Default:listComptes}

versAddOperation:
    path:   /versAddOperation
    defaults: {_controller: beanBundle:Default:versAddOperation}

saveOperation:
    path:   /saveOperation
    defaults: {_controller: beanBundle:Default:saveOperation}

getOperationsByCompte:
    path: /operationsByCompte/{id}
    defaults: {_controller: beanBundle:Default:getOperationsByCompte}

versModifierCompte:
    path: /versModifierCompte/{id}
    defaults: {_controller: beanBundle:Default:versModifierCompte}

updateCompte:
    path: /updateCompte/{id}
    defaults: {_controller: beanBundle:Default:mettreAjourCompte}

supprimerCompte:
    path: /supprimerCompte/{id}
    defaults: {_controller: beanBundle:Default:supprimerCompte}